### ISSUE TITLE
Please fix heroku deploy issue

### ISSUE THREAD

**Issue by amarhunter** [Artis7eeR/ForwardTagRemoverBot#6]
No app.json located in the repo URL provided.

Make sure that an app.json file exists in the project root directory.

**Comment by rez-f** [comment]
app.json is already in root project directory, you can see that.
All you have to do is accessing [this](https://heroku.com/deploy?template=https://github.com/Artis7eer/ForwardTagRemoverBot/tree/main) instead of the Deploy To Heroku Button in README.md, it's because the button link not updated yet since github change the primary branch name formerly master into main.
Change https://heroku.com/deploy?template=https://github.com/Artis7eer/ForwardTagRemoverBot/tree/master into https://heroku.com/deploy?template=https://github.com/Artis7eer/ForwardTagRemoverBot/tree/main
